image:
  file: Dockerfile

tasks:
  - name: Build
    command: >
      git clone https://github.com/PandaRose/v8js;
      cd v8js;
      phpize;
      ./configure --with-v8js=/opt/libv8-8.4 LDFLAGS="-lstdc++" CPPFLAGS="-DV8_COMPRESS_POINTERS";
      sh ../append.sh;
      make all -j4;
      make test;
      cp modules/v8js.so ../v8/v8js.so;
      cd ..;
      cp -r /opt/* v8/;
      cd v8;
      php -d extension="./v8js.so" test.php;
